spring:
  application:
    name: todo-app

  datasource:
    url: jdbc:postgresql://localhost:5432/ac_training
    username: postgres
    password: ponleu
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    show-sql: true

  main:
    allow-circular-references: true
#    allow-bean-definition-overriding: true  # Enable bean overriding

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
api:
  fakestore:
    url: https://fakestoreapi.com/products
cloudinary:
  cloud_name: dv78eaqnh
  api_key: 746111137433357
  api_secret: xgZiQ5e13Wm1uIaIP5BmaIwy_xI
logging:
  level:
    root: INFO
  file:
    path: ./logs/application.log   # Log output to a file
    max-size: 10MB                 # Max size for the log file
    max-history: 30                # Keep 30 archived logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Custom log pattern for the console
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # Custom log pattern for file


