spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://dpg-cr22b30gph6c73bel5o0-a.singapore-postgres.render.com:5432/dbcustomer
    username: dbcustomer_user
    password: 2EHz41n4zfKwZU9H9yjnVE5onR3GZy9Y
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    show-sql: true

  main:
    allow-circular-references: true

  jackson:
    serialization:
      write-dates-as-timestamps: false  # Correct format without comment inline

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

api:
  fakestore:
    url: https://fakestoreapi.com/products

cloudinary:
  cloud_name: dv78eaqnh
  api_key: 746111137433357
  api_secret: xgZiQ5e13Wm1uIaIP5BmaIwy_xI

logging:
  level:
    root: INFO
  file:
    path: ./logs/application.log   # Log output to a file
    max-size: 10MB                 # Max size for the log file
    max-history: 30                # Keep 30 archived logs

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Custom log pattern for the console
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # Custom log pattern for file


